<a href="https://colab.research.google.com/github/kinshuk-code-1729/Python-Training-Notebooks/blob/main/Day_11_PT03_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Day 11 Notebook 3***
## **Numpy Module :** Numpy stands for "Numeric Python".

In [14]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9]) # creates a 1-D array
print("Array :",arr)
print("Array Size :",arr.size)
print("Array Dimensions :",arr.shape)
print("Array type :",type(arr))

Array : [1 2 3 4 5 6 7 8 9]
Array Size : 9
Array Dimensions : (9,)
Array type : <class 'numpy.ndarray'>


In [15]:
arr1 = np.array([(1,2,3),(4,5,6),(7,8,9)]) # creates a 2-D Array
print("Array :",arr1)
print("Array Size :",arr1.size)
print("Array Dimensions :",arr1.shape)
print("Array type :",type(arr1))

Array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array Size : 9
Array Dimensions : (3, 3)
Array type : <class 'numpy.ndarray'>


In [16]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3) # converts 1-D array to passes "n X m" dimensional 2-D array
print("Array :",arr2)

Array : [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print("Size of Elements in Bytes :",arr2.itemsize) # gives size of elements in bytes

Size of Elements in Bytes : 8


In [18]:
# changing the dimensions of the existing array using "reshape()" method.
x = np.array([(54,35,75,97),(15,67,15,14)])
print("Before Reshaping.....")
print("Array :",x)
x = x.reshape(4,2)
print("Before Reshaping.....")
print("Array :",x)

Before Reshaping.....
Array : [[54 35 75 97]
 [15 67 15 14]]
Before Reshaping.....
Array : [[54 35]
 [75 97]
 [15 67]
 [15 14]]


In [19]:
x = np.arange(10).reshape(5,2) # another way to write matrix
print("array :",x) # <row> , <col>

array : [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
# array having less or more than passed dimensions will not be reshaped.
x = np.arange(10).reshape(3,2) # another way to write matrix
print("array :",x) # <row> , <col>

ValueError: ignored

In [21]:
p = np.zeros((2,3)) # a Matrix Filled with all elements zero
print("Matrix :",p) 

Matrix : [[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
p = np.ones((2,3)) # a Matrix Filled with all elements zero
print("Matrix :",p)

Matrix : [[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
p = np.eye(2,2) # creates an Identity matrix of "N X N" dimension
print("Matrix :",p)

Matrix : [[1. 0.]
 [0. 1.]]


In [24]:
p = np.diag([1,2,3]) # creates a diagonal matrix
print("Matrix :",p)

Matrix : [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
m = np.array([[54,44],[61,35]])
det = np.linalg.det(m) # finds determinant of a matrix
print("Determinant Value =",det)

Determinant Value = -794.0000000000003


In [ ]:
m = np.array([[54,44],[61,35]])
det = np.linalg.inv(m) # finds inverse of a matrix
print("Inverse Value =",det)

Inverse Value = [[-0.0440806   0.05541562]
 [ 0.0768262  -0.06801008]]


***If an array has a very small or very large determinant, then a call to det may overflow or underflow. This routine is more robust against such issues, because it computes the logarithm of the determinant rather than the determinant itself.***



In [25]:
m = np.array([[54,44],[61,35]])
(sign,lodget) = np.linalg.slogdet(m)
print(sign,lodget)
det = np.linalg.det(m) 
print("Determinant Value =",det)

-1.0 6.677083461247136
Determinant Value = -794.0000000000003


### **Most Important Concept Used in ML**

In [26]:
m = np.array([[8,4,3],[9,1,6],[2,7,4]])
print(m.sum(axis=1)) # Adding elements row-wise

[15 16 13]


In [27]:
print(m.sum(axis=0)) # Adding elements column-wise

[19 12 13]


### **Conversion of 'n' dimensional arrays into  single dimensional array.**
* *flatten( )* method
* *ravel( )* method

In [28]:
# flattening arrays
x = np.array([[0,1],[2,3]])
y = x.flatten()
print(y)
y[0] = 10
print("Array 2 is :",y)
print("Array 1 is :",x)

[0 1 2 3]
Array 2 is : [10  1  2  3]
Array 1 is : [[0 1]
 [2 3]]


In [29]:
x = np.array([[0,1],[2,3]])
y = x.ravel()
print(y)
y[0] = 10
print("Array 2 is :",y)
print("Array 1 is :",x)

[0 1 2 3]
Array 2 is : [10  1  2  3]
Array 1 is : [[10  1]
 [ 2  3]]


### Some Important Operations

In [30]:
x = np.array([4,5,6])
y = np.array([7,8,9])
print("Addition :",x + y)

Addition : [11 13 15]


In [31]:
x = np.array([4,5,6])
y = np.array([7,8,9])
print("Subtraction :",x - y)

Subtraction : [-3 -3 -3]


In [32]:
x = np.array([4,5,6])
y = np.array([7,8,9])
print("Multiplication :",x * y)

Multiplication : [28 40 54]


In [33]:
x = np.array([14,15,16])
y = np.array([7,8,9])
print("Integer Division :",x // y)

Integer Division : [2 1 1]


In [34]:
# Scalar Product not possible for different dimensional arrays.
a = np.array([np.arange(0,3), np.arange(0,6)])
b = np.array([np.arange(0,2), np.arange(2,4), np.arange(4,6)])
print('Matrix a is:',a)
print('Matrix b is:',b)
print('Scalar Product is:', a * 2)
print('Dot Product:', np.dot(a, b))

Matrix a is: [array([0, 1, 2]) array([0, 1, 2, 3, 4, 5])]
Matrix b is: [[0 1]
 [2 3]
 [4 5]]
Scalar Product is: [array([0, 2, 4]) array([ 0,  2,  4,  6,  8, 10])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


ValueError: ignored

In [35]:
# Addition of two arrays having different dimensions is not possible.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
print("Sum =",a + b)

ValueError: ignored

### ***Broadcast***
* size of each dimension should be same.
* size of one of the dimension should be 1.

In [36]:
x = np.array([[45,65],[74,34],[31,19]])
print("Matrix 1 :",x)
y = np.array([37,25,85])
z = np.array([34,24])
print("shape of x :",x.shape)
print("shape of y :",y.shape)
print("shape of z :",z.shape)
print("Addition of x and z :",x + z)

Matrix 1 : [[45 65]
 [74 34]
 [31 19]]
shape of x : (3, 2)
shape of y : (3,)
shape of z : (2,)
Addition of x and z : [[ 79  89]
 [108  58]
 [ 65  43]]


In [37]:
print(x + y)

ValueError: ignored

***Drawbacks of Numpy Module [See here](https://medium.com/@abhi16.2007/when-i-should-not-use-numpy-1e00aafb231b)***